const data = [
  {
    id: 1,
    formid: "1001",
    formname: "Access Rights Request Form",
    userid: "06344",
    username: "Borhan Hosen",
    unitheadstatus: "rejected",
    drheadstatus: null,
    isrmheadstatus: "Pending",
    implunitheadstatus: null,
    citostatus: "Pending",
  },
  {
    id: 2,
    formid: "1001",
    formname: "Access Rights Request Form",
    userid: "06344",
    username: "Borhan Hosen",
    unitheadstatus: "accepted",
    drheadstatus: null,
    isrmheadstatus: "Pending",
    implunitheadstatus: null,
    citostatus: "Pending",
  },

  {
    id: 1,
    formid: "1002",
    formname: "Access Control Request Form",
    userid: "06344",
    username: "Borhan Hosen",
    unitheadstatus: "pending",
    drheadstatus: "Pending",
    isrmheadstatus: "Pending",
    implunitheadstatus: null,
    citostatus: "Pending",
  },
  {
    id: 2,
    formid: "1002",
    formname: "Access Control Request Form",
    userid: "06344",
    username: "Borhan Hosen",
    unitheadstatus: "rejected",
    drheadstatus: "Pending",
    isrmheadstatus: "Pending",
    implunitheadstatus: null,
    citostatus: "Pending",
  },
  {
    id: 1,
    formid: "1003",
    formname: "Change Request Form",
    userid: "06344",
    username: "Borhan Hosen",
    unitheadstatus: "pending",
    drheadstatus: null,
    isrmheadstatus: "Pending",
    implunitheadstatus: "Pending",
    citostatus: "Pending",
  },
  {
    id: 2,
    formid: "1003",
    formname: "Change Request Form",
    userid: "06344",
    username: "Borhan Hosen",
    unitheadstatus: "pending",
    drheadstatus: null,
    isrmheadstatus: "Pending",
    implunitheadstatus: "Pending",
    citostatus: "Pending",
  },
];
export default data;
